/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdmonitionNode: typeof import('./src/components/AdmonitionNode/AdmonitionNode.vue')['default']
    BlockquoteNode: typeof import('./src/components/BlockquoteNode/BlockquoteNode.vue')['default']
    Button: typeof import('./src/components/button/Button.vue')['default']
    CheckboxNode: typeof import('./src/components/CheckboxNode/CheckboxNode.vue')['default']
    CodeBlockNode: typeof import('./src/components/CodeBlockNode/CodeBlockNode.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DefinitionListNode: typeof import('./src/components/DefinitionListNode/DefinitionListNode.vue')['default']
    EmojiNode: typeof import('./src/components/EmojiNode/EmojiNode.vue')['default']
    EmphasisNode: typeof import('./src/components/EmphasisNode/EmphasisNode.vue')['default']
    FallbackComponent: typeof import('./src/components/NodeRenderer/FallbackComponent.vue')['default']
    FootnoteNode: typeof import('./src/components/FootnoteNode/FootnoteNode.vue')['default']
    FootnoteReferenceNode: typeof import('./src/components/FootnoteReferenceNode/FootnoteReferenceNode.vue')['default']
    HardBreakNode: typeof import('./src/components/HardBreakNode/HardBreakNode.vue')['default']
    HeadingNode: typeof import('./src/components/HeadingNode/HeadingNode.vue')['default']
    HighlightNode: typeof import('./src/components/HighlightNode/HighlightNode.vue')['default']
    ImageNode: typeof import('./src/components/ImageNode/ImageNode.vue')['default']
    InlineCodeNode: typeof import('./src/components/InlineCodeNode/InlineCodeNode.vue')['default']
    InsertNode: typeof import('./src/components/InsertNode/InsertNode.vue')['default']
    LinkNode: typeof import('./src/components/LinkNode/LinkNode.vue')['default']
    ListItemNode: typeof import('./src/components/ListItemNode/ListItemNode.vue')['default']
    ListNode: typeof import('./src/components/ListNode/ListNode.vue')['default']
    MathBlockNode: typeof import('./src/components/MathBlockNode/MathBlockNode.vue')['default']
    MathInlineNode: typeof import('./src/components/MathInlineNode/MathInlineNode.vue')['default']
    MermaidBlockNode: typeof import('./src/components/MermaidBlockNode/MermaidBlockNode.vue')['default']
    NodeRenderer: typeof import('./src/components/NodeRenderer/NodeRenderer.vue')['default']
    ParagraphNode: typeof import('./src/components/ParagraphNode/ParagraphNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrikethroughNode: typeof import('./src/components/StrikethroughNode/StrikethroughNode.vue')['default']
    StrongNode: typeof import('./src/components/StrongNode/StrongNode.vue')['default']
    SubscriptNode: typeof import('./src/components/SubscriptNode/SubscriptNode.vue')['default']
    SuperscriptNode: typeof import('./src/components/SuperscriptNode/SuperscriptNode.vue')['default']
    TableNode: typeof import('./src/components/TableNode/TableNode.vue')['default']
    TextNode: typeof import('./src/components/TextNode/TextNode.vue')['default']
    ThematicBreakNode: typeof import('./src/components/ThematicBreakNode/ThematicBreakNode.vue')['default']
  }
}
