export function getLanguageIcon(lang: string): string {
  switch (lang) {
    case 'javascript':
    case 'js':
      return 'vscode-icons:file-type-js-official'
    case 'typescript':
    case 'ts':
      return 'vscode-icons:file-type-typescript'
    case 'jsx':
      return 'vscode-icons:file-type-reactjs'
    case 'tsx':
      return 'vscode-icons:file-type-reactts'
    case 'html':
      return 'vscode-icons:file-type-html'
    case 'css':
      return 'vscode-icons:file-type-css'
    case 'scss':
      return 'vscode-icons:file-type-scss'
    case 'json':
      return 'vscode-icons:file-type-json'
    case 'python':
    case 'py':
      return 'vscode-icons:file-type-python'
    case 'ruby':
    case 'rb':
      return 'vscode-icons:file-type-ruby'
    case 'go':
    case 'golang':
      return 'vscode-icons:file-type-go'
    case 'r':
      return 'vscode-icons:file-type-r'
    case 'java':
      return 'vscode-icons:file-type-java'
    case 'kotlin':
    case 'kt':
      return 'vscode-icons:file-type-kotlin'
    case 'c':
      return 'vscode-icons:file-type-c'
    case 'cpp':
    case 'c++':
      return 'vscode-icons:file-type-cpp'
    case 'cs':
    case 'csharp':
      return 'vscode-icons:file-type-csharp'
    case 'php':
      return 'vscode-icons:file-type-php'
    case 'scala':
      return 'vscode-icons:file-type-scala'
    case 'shell':
    case 'sh':
    case 'bash':
    case 'zsh':
    case 'powershell':
    case 'ps1':
    case 'bat':
    case 'batch':
      return 'vscode-icons:file-type-powershell'
    case 'sql':
      return 'vscode-icons:file-type-sql'
    case 'yaml':
    case 'yml':
      return 'vscode-icons:file-type-yaml'
    case 'markdown':
    case 'md':
      return 'vscode-icons:file-type-markdown'
    case 'xml':
      return 'vscode-icons:file-type-xml'
    case 'rust':
    case 'rs':
      return 'vscode-icons:file-type-rust'
    case 'swift':
      return 'vscode-icons:file-type-swift'
    case 'perl':
      return 'vscode-icons:file-type-perl'
    case 'lua':
      return 'vscode-icons:file-type-lua'
    case 'haskell':
      return 'vscode-icons:file-type-haskell'
    case 'erlang':
      return 'vscode-icons:file-type-erlang'
    case 'clojure':
      return 'vscode-icons:file-type-clojure'
    case 'vue':
      return 'vscode-icons:file-type-vue'
    case 'svg':
      return 'vscode-icons:file-type-svg'
    case 'mermaid':
      return 'vscode-icons:file-type-mermaid' // Or 'mdi:graph' if mermaid icon missing
    case 'dart':
      return 'vscode-icons:file-type-dartlang'
    case 'assembly':
      return 'vscode-icons:file-type-assembly'
    case 'dockerfile':
      return 'vscode-icons:file-type-docker'
    case 'fortran':
      return 'vscode-icons:file-type-fortran'
    case 'lisp':
      return 'vscode-icons:file-type-lisp'
    case 'ocaml':
      return 'vscode-icons:file-type-ocaml'
    case 'prolog':
      return 'vscode-icons:file-type-prolog'
    case 'groovy':
      return 'vscode-icons:file-type-groovy'
    case 'matlab':
      return 'vscode-icons:file-type-matlab'
    case 'cobol':
      return 'vscode-icons:file-type-cobol'
    case 'ada':
      return 'vscode-icons:file-type-ada'
    case 'julia':
      return 'vscode-icons:file-type-julia'
    case 'elixir':
      return 'vscode-icons:file-type-elixir'
    case 'vb.net':
      return 'vscode-icons:file-type-vb'
    case 'nim':
      return 'vscode-icons:file-type-nim'
    case 'crystal':
      return 'vscode-icons:file-type-crystal'
    case 'd':
      return 'vscode-icons:file-type-dlang'
    case 'applescript':
      return 'vscode-icons:file-type-applescript'
    case 'solidity':
      return 'vscode-icons:file-type-solidity'
    case 'objectivec':
      return 'vscode-icons:file-type-objectivec'
    case 'objectivecpp':
      return 'vscode-icons:file-type-objectivecpp'
    case 'terraform':
      return 'vscode-icons:file-type-terraform'
    case 'plain':
    case 'text':
      return 'vscode-icons:file-type-text' // Icon for plain text
    default:
      return 'lucide:square-code' // Fallback icon
  }
}

// 映射一些常见语言的显示名称
export const languageMap: Record<string, string> = {
  js: 'JavaScript',
  ts: 'TypeScript',
  jsx: 'JSX',
  tsx: 'TSX',
  html: 'HTML',
  css: 'CSS',
  scss: 'SCSS',
  json: 'JSON',
  py: 'Python',
  python: 'Python',
  rb: 'Ruby',
  go: 'Go',
  java: 'Java',
  c: 'C',
  cpp: 'C++',
  cs: 'C#',
  php: 'PHP',
  sh: 'Shell',
  bash: 'Bash',
  sql: 'SQL',
  yaml: 'YAML',
  md: 'Markdown',
  '': 'Plain Text',
  plain: 'Plain Text',
}
